version: '3.8'

services:
  indiana-auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${AUTH_API_PORT}:${AUTH_API_PORT}
    environment:
      - NODE_ENV=development
      - MONGO_DB_URI=mongodb://${DATABASE_HOST_NAME}:${DATABASE_PORT}/
    container_name: auth-api
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
      - .env.production
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
