# Main CI/CD workflow
name: Indiana Node.js main branch workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Read .nvmrc
          id: nvmrc
          run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test